### ISSUE TITLE
[HU-P3] Servicio de logs

### ISSUE THREAD

**Issue by amerigal** [amerigal/gestor-recibos#32]
Como programador, me gustaría disponer de un servicio de logs para registrar la actividad de la aplicación.

**Comment by JJ** [comment]
No deberías usar esto como historias de usuario, son simples issues. Aunque les pongas la `P`, siguen teniendo la misma etiqueta que las HUs "reales"
Como issues tampoco sirven, porque no plantean un problema. Recuerda que un issue siempre dice por qué quieres algo, no lo que quieres.

**Comment by amerigal** [comment]
Lo corrijo en las siguientes :+1:
